### ISSUE TITLE
Add argument to getNextPage

### ISSUE THREAD

**Issue by funivan** [xparse/RecursivePagination#2]
``` php
$page = $paginator->getNextPage('.//*[@id="paginator"]//a/@href')
```

**Comment by funivan** [comment]
ping @ganchclub

**Comment by ganchclub** [comment]
do we really need this feature?

**Comment by funivan** [comment]
yes

**Comment by funivan** [comment]
We can do following thing:

``` php
$robot->paginatorFetcher->getNextPage('.//*[@id="paginator"]//a/@href')
```

Bet I don`t know if we need to rewrite default xpath or just append. What do you think @ganchclub?

**Comment by ganchclub** [comment]
I was thinking about the same thing, so the question was asked about real need. 
I think we should append it to default xpath array

**Comment by funivan** [comment]
We shoud think about xpath not about how to init recursive pagination but how to fetch next page. So implement this feature. Just add xpath to default one

**Comment by ganchclub** [comment]
should it be only string or array too?

**Comment by funivan** [comment]
array or string. you need to extract some logic from constructor to private method addXpath and call it in both cases

**Comment by ganchclub** [comment]
ok
